[package]
name = "opentelemetry-instrumentation-tower"
edition = "2021"
version = "0.16.0"
license = "Apache-2.0"
description = "OpenTelemetry Metrics Middleware for Tower-compatible Rust HTTP servers"
homepage = "https://github.com/open-telemetry/opentelemetry-rust-contrib"
repository = "https://github.com/open-telemetry/opentelemetry-rust-contrib"
documentation = "https://docs.rs/tower-otel-http-metrics"
readme = "README.md"
include = ["src/"]

[features]
default = []
axum = ["dep:axum"]

[dependencies]
axum = { features = ["matched-path", "macros"], version = "0.8", default-features = false, optional = true }
futures-util = { version = "0.3", default-features = false }
http = { version = "1", features = ["std"], default-features = false }
http-body = { version = "1", default-features = false }
opentelemetry = { version = "0.30.0", features = ["futures-core", "futures-sink", "pin-project-lite", "metrics"], default-features = false }
pin-project-lite = { version = "0.2", default-features = false }
tower-service = { version = "0.3", default-features = false }
tower-layer = { version = "0.3", default-features = false }

[dev-dependencies]

[lints]
workspace = true